{"name": "连接蓝牙", "status": "failed", "statusDetails": {"message": "AssertionError: assert False == True", "trace": "self = <DB_Autotest.main.TestIVI object at 0x0000021857D7AC10>\n\n    @allure.id(\"test_08_connect_bluetooth\")\n    @allure.title(\"连接蓝牙\")\n    @allure.description(\"\"\"\n        TestId:\n            test_08_connect_bluetooth\n        TestTitle:\n            连接蓝牙\n        TestDescription:\n            连接蓝牙\n        TestPrecondition:\n            1、周边存在蓝牙名为test,且已经连接过此蓝牙设备\n        TestStep:\n            1、连接test蓝牙设备\n        TestExpectation:\n            1、蓝牙连接成功\n                \"\"\")\n    def test_08_connect_bluetooth(self):\n        result = self.a19.connect_bluetooth()\n>       assert result == True\nE       assert False == True\n\nmain.py:196: AssertionError"}, "description": "\n        TestId:\n            test_08_connect_bluetooth\n        TestTitle:\n            连接蓝牙\n        TestDescription:\n            连接蓝牙\n        TestPrecondition:\n            1、周边存在蓝牙名为test,且已经连接过此蓝牙设备\n        TestStep:\n            1、连接test蓝牙设备\n        TestExpectation:\n            1、蓝牙连接成功\n                ", "attachments": [{"name": "log", "source": "cad3c0aa-6856-4c9d-a5ac-ef4a2728d2e1-attachment.txt", "type": "text/plain"}], "start": 1713439664794, "stop": 1713439711265, "uuid": "58a5988c-abe1-4266-8d27-bd627bd44f26", "historyId": "34bdc8043bb1a386a26afbe0a8f09b38", "testCaseId": "34bdc8043bb1a386a26afbe0a8f09b38", "fullName": "main.TestIVI#test_08_connect_bluetooth", "labels": [{"name": "as_id", "value": "test_08_connect_bluetooth"}, {"name": "suite", "value": "main"}, {"name": "subSuite", "value": "TestIVI"}, {"name": "host", "value": "test-1"}, {"name": "thread", "value": "21404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}